### ISSUE TITLE
Gemini model ignores model.key

### ISSUE THREAD

**Issue by wolfmanstout** [simonw/llm-gemini#15]
Unlike the OpenAI and Claude 3 plugins, the Gemini model implementation is using llm.get_key() directly instead of self.get_key(), so it ignores any key that might have been set on the model: https://github.com/simonw/llm-gemini/blob/9652493f6d52eadd4c7552b6016b5c0eddc876cb/llm_gemini.py#L59

Compare to: https://github.com/simonw/llm-claude-3/blob/18d562a730643753ee0d65c7220deac2e9cde689/llm_claude_3.py#L109

**Comment by simonw** [comment]
Proof that this works:
```bash
llm -m gemini-1.5-pro-latest --key x 'hi'
```
Outputs:
> `Error: API key not valid. Please pass a valid API key.`
